### ISSUE TITLE
New board revision compatibility

### ISSUE THREAD

**Issue by ssalb** [k-ross/indi-wmh-focuser#1]
Hi @k-ross 

I've been trying to give this a try but couldn't, my motor would just hold and not turn. I thought it was my wiring until I noticed there's a new revision v2.1 of this board ([Link here](https://www.waveshare.com/wiki/Stepper_Motor_HAT)).
I tested with their demo code both the old and new versions, and as expected only the new demo code works fine with my board.

I tried to look at the differences in the bcm2835 source code, but I can't really understand this that easy (I'm a different kind of dev) so I'm afraid that instead of attempting a PR, I can only file an issue and hope you'll find the time and the way to support this new revision (assuming that's the problem)

Thanks!

**Comment by k-ross** [comment]
Looks like they reversed the polarity of the Enable pin, previously active low, now active high. Can you test something for me? In DRV8825.c, anywhere you see:

DEV_Digital_Write(Motor.EnablePin, 0);

replace it with

DEV_Digital_Write(Motor.EnablePin, 1);

and of course, any place you see:

DEV_Digital_Write(Motor.EnablePin, 1);

replace it with

DEV_Digital_Write(Motor.EnablePin, 0);

Can you give that a test and let me know if that works? If it does, then I'll have to add an option in the INDI control panel.

Thanks!
-- Kevin

**Comment by ssalb** [comment]
Awesome! yes, that did the trick. I feel a bit embarrassed now for how simple it was :D

**Comment by k-ross** [comment]
Thanks for confirming that works. I'll eventually get around to adding an option to the control panel.

**Comment by k-ross** [comment]
Fixed in 828e68d68523eb1a3cbc54067d4220f6624ef6cd
